### ISSUE TITLE
Decrypt fails with Twocanoes CTK plugin and keychain-pkcs11

### ISSUE THREAD

**Issue by Cerebus** [kenh/keychain-pkcs11#17] opened 2024-03-06 19:50 UTC
This is possibly an issue with their plugin, but posting here in case there's a fix here, a workaround, or additional debugging I can sent on to the vendor.

```
 > pluginkit -m -p com.apple.ctk-tokens
     [...]
     com.twocanoes.Smart-Card-Utility.pivtoken(4.5)
```

Attempting operations with the card (e.g., through `gpgsm`) gives me a generic error, but `pkcs11-tool` throws additional stuff:

```
> pkcs11-tool -O --module /usr/local/lib/keychain-pkcs11.dylib
Using slot 0 with a present token (0x0)
Certificate Object; type = X.509 cert
  label:      Certificate For PIV Authentication (REDACTED)
  subject:    DN: C=US, O=U.S. Government, OU=DoD, OU=PKI, OU=CONTRACTOR, CN=REDACTED
  serial:     REDACTED
  ID:         00
Public Key Object; RSA 2048 bits
  label:      Certificate For PIV Authentication (REDACTED)
  ID:         00
warning: PKCS11 function C_GetAttributeValue(VERIFY_RECOVER) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

  Usage:      encrypt, verify
  Access:     local
  ...
```

**Comment by kenh** [comment] 2024-03-06 20:04
Hm. This feels like pkcs11-tool (or the library it calls) is being RATHER picky.

I didn't implement the attribute ```CKA_VERIFY_RECOVER```. My reading of PKCS#11 v2.40 is that if you don't have an attribute you're supposed to return the return code ```CKF_ATTRIBUTE_TYPE_INVALID``` ... which I do. It seems kind of lousy that it's failing if it can't find that attribute.

You can use the MacOS X ```log``` command to dump detailed logging information from the keychain-pkcs11 library (see ```man keychain-pkcs11``` for the exact format of the log command). If this is the issue adding the ```CKA_VERIFY_RECOVER``` attribute is a simple enough fix.

**Comment by Cerebus** [comment] 2024-03-06 20:12
I forgot all about that.  Here's the salient error:

```
2024-03-06 14:11:31.659110-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] SecKeyCreateDecryptedData failed: Error Domain=NSOSStatusErrorDomain Code=-50 "algid:encrypt:RSA:PKCS1: algorithm not supported by the key <SecKeyRef:('com.twocanoes.Smart-Card-Utility.pivtoken:FT_CF7BABC858BE') 0x60000026ea40>" (paramErr: error in user parameter list) UserInfo={numberOfErrorsDeep=0, NSDescription=algid:encrypt:RSA:PKCS1: algorithm not supported by the key <SecKeyRef:('com.twocanoes.Smart-Card-Utility.pivtoken:FT_CF7BABC858BE') 0x60000026ea40>} (-50)
```

I should add, the `gnupg-pkcs11-scd` is perfectly happy with the exact same operation using `opensc-pkcs11` or when I remove the Twocanoes CTK plugin but retain `keychain-pkcs11`.

**Comment by kenh** [comment] 2024-03-06 20:27
> ```
> 2024-03-06 14:11:31.659110-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] SecKeyCreateDecryptedData failed: Error Domain=NSOSStatusErrorDomain Code=-50 "algid:encrypt:RSA:PKCS1: algorithm not supported by the key <SecKeyRef:('com.twocanoes.Smart-Card-Utility.pivtoken:FT_CF7BABC858BE') 0x60000026ea40>" (paramErr: error in user parameter list) UserInfo={numberOfErrorsDeep=0, NSDescription=algid:encrypt:RSA:PKCS1: algorithm not supported by the key <SecKeyRef:('com.twocanoes.Smart-Card-Utility.pivtoken:FT_CF7BABC858BE') 0x60000026ea40>} (-50)
> ```

That error is, I think, relatively self-explanatory; it's trying to do the decrypt operation and the TwoCanoes CTK plugin is saying, "That's not supported for that key", which usually means that the key is marked as supporting sign only or the algorithm isn't compatible in some other way (I know the algorithm is listed as ```algid:encrypt:RSA:PKCS1``` but that is the constant for the algorithm type; it says ```encrypt``` even when it is doing a decrypt operation).

I am willing to believe that I am doing something wrong, but from where I'm sitting right now it doesn't seem like I am; that part of the code is very straightforward. The only thing I could think of that is going wrong is that maybe you're not picking the right key when using the TwoCanoes CTK plugin. E.g., normally a PIV authentication key can't do decryption. You didn't show what ```pkcs11-tool``` shows for your private key object; for my PIV certificate the only supported key usage is ```sign```.

**Comment by Cerebus** [comment] 2024-03-06 20:58
I'm certain test file is encrypted with the right key pubkey; I verified by attempting with the wrong key and it verifiably obeys keyUsage.

I'm not sure how to tie the output from `pkcs11-tool` to the SecKeyRef in the above error, so I can't tell if the right key is being selected.  Am I missing something?

Per the vendor's [pseudo-FAQ](https://twocanoes.com/knowledge-base/smart-card-utility-commands/), I get nothing for my test operation, so I read this as the reject is in their plugin, and the operation never reaches the card:
```
> log stream --predicate '(subsystem == "com.apple.CryptoTokenKit") && (category == "APDULog")'

Filtering the log data using "subsystem == "com.apple.CryptoTokenKit" AND category == "APDULog""
```

**Comment by kenh** [comment] 2024-03-06 21:25
> I'm not sure how to tie the output from `pkcs11-tool` to the SecKeyRef in the above error, so I can't tell if the right key is being selected. Am I missing something?

Unfortunately that's a bit non-obvious, but based on some intelligent guesses you should be able to figure it out.  Specifically before the call to ```C_Decrypt``` there should be a call to ```C_DecryptInit``` and it should have a log entry like this:

```
session = 0, mech = 1, key = 3
```

```key``` should correspond to the object identifier. Unfortunately it's a little hard to match that up with the output of ```pkcs11-tool```, but here are some hints.

For each identity, there are three objects: Object 1 will be the certificate (```CKO_CERTIFICATE```). Object 2 will be the public key (```CKO_PUBLIC_KEY```) and Object 3 will be the private key (```CKO_PRIVATE_KEY```). So assuming you want to use the private key to decrypt you should be using an object identifier that is a multiple of 3.  ```pkcs11-tool``` will print the objects in order so you should be able to figure out which card identity corresponds to the key object being selected.

**Comment by Cerebus** [comment] 2024-03-06 21:26
🤔  Signing also fails:

```
2024-03-06 15:26:09.784317-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_SignInit called
2024-03-06 15:26:09.784441-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 1, mechanism = <private>, object = 6
2024-03-06 15:26:09.784483-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Signing algorithm chosen: algid:sign:RSA:digest-PKCS1v15
2024-03-06 15:26:09.784568-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Digest signing algorithm chosen: (null)
2024-03-06 15:26:09.784649-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Digest algorithm chosen: CKM_RSA_PKCS_KEY_PAIR_GEN
2024-03-06 15:26:09.784717-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_SignInit returning <private>
2024-03-06 15:26:09.784759-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Sign called
2024-03-06 15:26:09.784839-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 1, indata = 0x600001944e00, inlen = 51, outdata = 0x60000305ad00, outlen = 256
2024-03-06 15:26:19.859246-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] SecKeyCreateSignature failed: Error Domain=CryptoTokenKit Code=-7 "(null)"
2024-03-06 15:26:19.859300-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Sign returning <private>
```

**Comment by Cerebus** [comment] 2024-03-06 21:30
... and then signing worked ...

🤦 

```
2024-03-06 15:32:55.849567-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_SignInit called
2024-03-06 15:32:55.849601-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 1, mechanism = <private>, object = 6
2024-03-06 15:32:55.849635-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Signing algorithm chosen: algid:sign:RSA:digest-PKCS1v15
2024-03-06 15:32:55.849665-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Digest signing algorithm chosen: (null)
2024-03-06 15:32:55.849694-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Digest algorithm chosen: CKM_RSA_PKCS_KEY_PAIR_GEN
2024-03-06 15:32:55.849764-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_SignInit returning <private>
2024-03-06 15:32:55.849793-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Sign called
2024-03-06 15:32:55.849851-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 1, indata = 0x6000019576c0, inlen = 51, outdata = 0x0, outlen = 0
2024-03-06 15:32:55.849957-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] sig is NULL, returning an output size of 256
2024-03-06 15:32:55.850062-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Sign returning <private>
2024-03-06 15:32:55.850130-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Sign called
2024-03-06 15:32:55.850181-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 1, indata = 0x6000019576c0, inlen = 51, outdata = 0x60000305d900, outlen = 256
2024-03-06 15:33:05.243740-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Sign returning <private>
```

Literally minutes apart from the signing failure above, so WTH?

I appreciate the help debugging, I updated the vendor and pointed them here to this issue, so maybe I'll get something from them.

**Comment by Cerebus** [comment] 2024-03-06 21:52
So here's the full decrypt session, from DecryptInit:

```
2024-03-06 15:50:32.175195-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_DecryptInit called
2024-03-06 15:50:32.175239-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 0, mech = 1, key = 9
2024-03-06 15:50:32.175316-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] Encryption algorithm chosen: algid:encrypt:RSA:PKCS1
2024-03-06 15:50:32.175423-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_DecryptInit returning <private>
2024-03-06 15:50:32.175526-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Decrypt called
2024-03-06 15:50:32.175622-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] session = 0, indata = 0x600003059700, inlen = 256, outdata = 0x600003064000, outlen = 256
2024-03-06 15:50:32.210005-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] SecKeyCreateDecryptedData failed: Error Domain=NSOSStatusErrorDomain Code=-50 "algid:encrypt:RSA:PKCS1: algorithm not supported by the key <SecKeyRef:('com.twocanoes.Smart-Card-Utility.pivtoken:FT_CF7BABC858BE') 0x60000026ea40>" (paramErr: error in user parameter list) UserInfo={numberOfErrorsDeep=0, NSDescription=algid:encrypt:RSA:PKCS1: algorithm not supported by the key <SecKeyRef:('com.twocanoes.Smart-Card-Utility.pivtoken:FT_CF7BABC858BE') 0x60000026ea40>} (-50)
2024-03-06 15:50:32.210059-0600 0xada97e   Debug       0x0                  67918  0    gnupg-pkcs11-scd: (keychain-pkcs11.dylib) [mil.navy.nrl.cmf.pkcs11:general] C_Decrypt returning <private>
```

`key=9` seems to be the correct object:

```
Private Key Object; RSA
  label:      key-Certificate For Key Management
  ID:         02
```

Ordering of the objects on the card is (usually):
- piv auth
- sign
- key management
- card auth

ID starts at 0, so `key=9` becomes `ID=02`, so that's the right card object.

**Comment by kenh** [comment] 2024-03-07 01:06
Hm, wait, are you on Sonoma? Which version?

There was a bug with Sonoma 14.3 where decryption with a key on a Smartcard failed; this affected everything that used the Apple Security framework. It would have not affected things that bypass that framework (like ```opensc```). This was fixed in 14.3.1.

As for the signing failing then working ... I have no idea on that one. That sure sounds like an issue with the Tucanoes plugin.

**Comment by Cerebus** [comment] 2024-03-07 14:21
Yeah, I thought of that b/c I was tracking that bug on the Apple fed-talk list.  I'm on 14.3.1.  I can't seem to disable the twocanoes token.  I can `security smartcards token -d com.twocanoes.Smart-Card-Utility.pivtoken` but it doesn't seem to have any effect.  I'll wager if I remove it entirely everything will go back to working.  🤔 

The only reason I'm dealing with this is the (now discontinued) slim BT reader is a nice form factor and it was given to me.

I feel like a GnuPG scdaemon that talks directly to CTK would be a nice to have, as the only reason I'm still using pkcs11 at all is b/c I use `gpgsm` for commit signing and Emacs `message-mode` with EasyPG for S/MIME.  I should go look for one, maybe OpenSC has done this.

**Comment by kenh** [comment] 2024-03-07 15:08
> I feel like a GnuPG scdaemon that talks directly to CTK would be a nice to have, as the only reason I'm still using pkcs11 at all is b/c I use `gpgsm` for commit signing and Emacs `message-mode` with EasyPG for S/MIME. I should go look for one, maybe OpenSC has done this.

I don't think that would help you here? ```keychain-pkcs11``` is talking to CTK (well, indirectly via the Security framework) and it's getting this error; anything else that calls those same APIs would get the same error. Unless you mean call the CTK APIs directly, but as far as I can tell basically nobody does that because it requires a ton of work to talk to each specific card.

If the issue is this one specific Smartcard reader you want to use ... well, I see a ton of Smartcard readers on Amazon that seem to work natively on MacOS X in the $15 range.

**Comment by Cerebus** [comment] 2024-03-07 20:21
I wonder if the bug in 14.3.0 `Security.framework` requires an update to CTK plugins.  🤔

**Comment by kenh** [comment] 2024-03-07 20:29
> I wonder if the bug in 14.3.0 `Security.framework` requires an update to CTK plugins. 🤔

Very possible! The same error (```(paramErr: error in user parameter list)```) was returned for the same exact case (decrypt on smartcard).

I am feeling this isn't a ```keychain-pkcs11``` bug; if you don't have any objections I'd like to close this issue.

**Comment by Cerebus** [comment] 2024-03-07 20:43
Appreciate the help.

**Comment by Cerebus** [comment] 2024-03-11 18:11
Reopening for comment.  Got this from the vendor:

> It looks like the issue is that we return that we support algid:encrypt:RSA:Raw and GnuPG requires
algid:encrypt:RSA:PKCS1. I was using algid:encrypt:RSA:PKCS1 before when testing with signing / decrypting in Mail, and had to change it to Raw for it to work. I'll need to set up a test environment to test and getting it working.

**Comment by kenh** [comment] 2024-03-11 18:36
Huh. I can't speak for Mail.app, but in my experience almost all apps request PKCS1 (this corresponds to the PKCS#11 mechanism ```CKM_RSA_PKCS```).  I realize that you could support PKCS1 via Raw by constructing the ASN.1 digest yourself, but in my testing the stock Apple Security framework smartcard drivers only supported Raw for decrypt (which I guess is what it needs to do, but still ...). I was under the impression that if you supported RSA you had to handle all of the supported algorithms.

I see there is a function ```SecKeyIsAlgorithmSupported``` which I didn't use; I suppose I should do some experimentation. But I honestly think they should support PKCS1 because that is VERY common; I don't know why they can't do both.

**Closed as completed** 2024-03-11 18:40 UTC
